const items = [
    {
        id: '001',
        image: 'img1.png',
        company: 'Peter England ',
        item_name: 'Men Slim Fit Printed Pure Cotton Formal Shirt',
        original_price: 1999,
        current_price: 1699,
        discount_percentage: 15,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 140,
        },
    },
    {
        id: '002',
        image: 'img2.png',
        company: 'Bewakoof',
        item_name: 'Black Graphic Printed Oversized Cotton T-Shirt',
        original_price: 1499,
        current_price: 674,
        discount_percentage: 52,
        return_period: 14,
        delivery_date: '10 Nov 2023',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'img3.png',
        company: 'SINGNI',
        item_name: 'Women Purple Ethnic Motifs Embroidered Mirror Work Kurta with Trousers & Dupatta',
        original_price: 4999,
        current_price: 1149,
        discount_percentage: 77,
        return_period: 14,
        delivery_date: '10 Nov 2023',
        rating: {
            stars: 4.1,
            count: 1300,
        },
    },
    {
        id: '004',
        image: 'img4.png',
        company: 'ADIDAS',
        item_name: 'Unisex Lace-Up Running Shoes',
        original_price: 9999,
        current_price: 6499,
        discount_percentage: 35,
        return_period: 14,
        delivery_date: '10 Nov 2023',
        rating: {
            stars: 4.3,
            count: 100,
        },
    },
    {
        id: '005',
        image: 'img5.png',
        company: 'Anouk',
        item_name: 'Men Blue & White Printed Straight Kurta',
        original_price: 2199,
        current_price: 703,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '10 Nov 2023',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'img6.png',
        company: 'Sztori',
        item_name: 'Plus Size Women Navy Blue Pure Cotton Denim Jacket',
        original_price: 3399,
        current_price: 1499,
        discount_percentage: 58,
        return_period: 14,
        delivery_date: '10 Nov 2023',
        rating: {
            stars: 4.6,
            count: 149,
        },
    },
    {
        id: '007',
        image: 'img7.png',
        company: 'Kook N Keech',
        item_name: 'Men Snow White Mid-rise Street Look Parade Technical Ombre Joggers',
        original_price: 1599,
        current_price: 747,
        discount_percentage: 60,
        return_period: 14,
        delivery_date: '10 Nov 2023',
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'img8.png',
        company: 'Ted Baker',
        item_name: 'Women Grey Melange Solid Smart Casual Blazer',
        original_price: 5699,
        current_price: 1937,
        discount_percentage: 66,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.4,
            count: 5200,
        },
    }
];